# Generated by Django 6.0.2 on 2026-03-03 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('created_at', models.DateField(auto_now=True, null=True)),
                ('published', models.BooleanField(default=False)),
                ('category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CorporationsWithLPStores',
            fields=[
                ('created_at', models.DateField(auto_now=True, null=True)),
                ('corporation_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('home_station_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('ticker', models.CharField(max_length=20)),
                ('war_eligible', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MarketGroups',
            fields=[
                ('created_at', models.DateField(auto_now=True, null=True)),
                ('market_group_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('published', models.BooleanField(default=False)),
                ('type_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('capacity', models.FloatField(blank=True, null=True)),
                ('mass', models.FloatField(blank=True, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('packaged_volume', models.FloatField(blank=True, null=True)),
                ('radius', models.FloatField(blank=True, null=True)),
                ('portion_size', models.IntegerField(blank=True, null=True)),
                ('graphic_id', models.IntegerField(blank=True, null=True)),
                ('icon_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CorporationsLpItemTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True, null=True)),
                ('ak_cost', models.IntegerField(blank=True, null=True)),
                ('isk_cost', models.BigIntegerField(blank=True, null=True)),
                ('lp_cost', models.IntegerField(blank=True, null=True)),
                ('offer_id', models.IntegerField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('required_items', models.JSONField(blank=True, null=True)),
                ('corporation_id', models.ForeignKey(db_column='corporation_id', on_delete=django.db.models.deletion.CASCADE, related_name='lp_store_offers', to='industry.corporationswithlpstores')),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('created_at', models.DateField(auto_now=True, null=True)),
                ('published', models.BooleanField(default=False)),
                ('group_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='industry.categories')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MarketPrices',
            fields=[
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('type_id', models.OneToOneField(db_column='type_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='market_prices', serialize=False, to='industry.types')),
                ('adjusted_price', models.FloatField(blank=True, null=True)),
                ('average_price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='types',
            name='group_id',
            field=models.ForeignKey(blank=True, db_column='group_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='types', to='industry.groups'),
        ),
        migrations.AddField(
            model_name='types',
            name='market_group_id',
            field=models.ForeignKey(blank=True, db_column='market_group_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='types', to='industry.marketgroups'),
        ),
        migrations.AddField(
            model_name='corporationswithlpstores',
            name='type_id',
            field=models.ManyToManyField(through='industry.CorporationsLpItemTypes', to='industry.types'),
        ),
        migrations.AddField(
            model_name='corporationslpitemtypes',
            name='type_id',
            field=models.ForeignKey(db_column='type_id', on_delete=django.db.models.deletion.CASCADE, related_name='lp_store_offers', to='industry.types'),
        ),
        migrations.AlterUniqueTogether(
            name='corporationslpitemtypes',
            unique_together={('type_id', 'corporation_id')},
        ),
    ]
