# Generated by Django 6.0.2 on 2026-02-25 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0012_alter_corporationslpitemtypes_corporation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporationslpitemtypes',
            name='isk_cost',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
