# Generated by Django 6.0.2 on 2026-03-11 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0001_initial'),
        ('watchlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='watchlistitem',
            unique_together={('watchlist', 'item', 'corporation')},
        ),
    ]
