# Generated by Django 6.0.2 on 2026-04-07 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0002_alter_watchlistitem_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
