# Generated by Django 6.0.2 on 2026-04-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0003_watchlist_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='description',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
